from cnnphase import *

predict = CNNPredict()
predict.SetDevice('cuda')
predict.SetModel(NNModel)
predict.SetExpData('DeepLeaningAmp.npy', mask=500)
predict.SetTrainedNN("CP600_2022-03-05_00.55.pth")
predict.SetOutputFile('outputGold.py')
predict.SetLRStepSize(25)
predict.AddLR(1e-4)
predict.AddLR(1e-5)
predict.SetGamma(0.75)
predict.AddOptimiser(optim.ASGD)
predict.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
predict.AddScheduler(ss.StepLR)
predict.AddScheduler(ss.StepLR)
predict.SetNEpochs(1000)
predict.SetOpStep(500)
predict.Iterate_Predict()
predict.PlotLoss()