from cnnphaseAh import *

predict = CNNPredict()
predict.SetDevice('cuda')
predict.SetModel(NNModel)
predict.SetExpData('DeepLeaningAmp.npy', mask=500)
predict.SetTrainedNN("CP600_2022-03-05_00.55.pth")
predict.SetOutputFile('outputGold02.py')
predict.SetLRStepSize(500)
predict.AddLR(1e-4)
predict.AddLR(5e-5)
predict.AddLR(1e-5)
predict.AddLR(5e-6)
predict.SetGamma(0.9)
predict.AddOptimiser(optim.ASGD)
predict.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
predict.AddOptimiser(optim.ASGD)
predict.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
predict.AddScheduler(ss.StepLR)
predict.AddScheduler(ss.StepLR)
predict.AddScheduler(ss.StepLR)
predict.AddScheduler(ss.StepLR)
predict.SetNEpochs(40000)
predict.SetOpStep(10000)
predict.TransferPredict()
predict.PlotLoss()