from cnn import *

predict = CNNPredict()
predict.SetDeviceType('cuda')
predict.SetModel(NNModel)
predict.SetExpData('expdata.py', mask=500)
predict.SetTrainedNN('CP200.pth')
predict.SetOutputFile('output.py')
predict.Predict()
predict.InitializeWeightsPre('CP200.pth')
predict.SetLRStepSize(25)
predict.SetLR(1e-5,2e-3)
predict.SetGamma(0.75)
predict.SetNOptimisers(N=1)
predict.SetOptimiser1('ADAM')
predict.SetScheduler1('StepLR')
predict.SetNEpochs(1000)
predict.iterate_predict()
predict.PlotLoss()