from cnnphase06 import *


def Train():
	cnn = CNNTrain()
	cnn.SetDevice('cuda')
	cnn.SetInputData('fs_amps.npy')
	cnn.SetTargetData('rs_objs.npy')
	cnn.SetModel(NNModel, momentum = 0.9, checkpoints = False)
	cnn.SetValidSize(0.1)
	cnn.SplitData()
	cnn.SetBatchSize(16)
	cnn.LoadSplitTrain(loadtype='train')
	cnn.LoadSplitTrain(loadtype='test')
	#cnn.LoadWeights("CP.pth")
	cnn.InitialiseWeights(nn.init.kaiming_normal_, mode='fan_in', nonlinearity='leaky_relu')
	#cnn.InitialiseWeights(nn.init.xavier_normal_)
	cnn.SetLRStepSize(25)
	cnn.AddLR(1e-4)
	cnn.AddLR(1e-5)
	#cnn.AddLR(5e-5)
	#cnn.AddLR(5e-6)
	cnn.SetGamma(0.9)
	cnn.AddOptimiser(optim.ASGD)
	cnn.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
	#cnn.AddOptimiser(optim.ASGD)
	#cnn.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
	#cnn.AddOptimiser(optim.SGD, momentum=0.9)
	#cnn.AddOptimiser(optim.RMSprop, alpha=0.99, eps=1e-08, weight_decay=0, momentum=0.9, centered=False)
	cnn.AddScheduler(ss.StepLR)
	cnn.AddScheduler(ss.StepLR)
	#cnn.AddScheduler(ss.StepLR)
	#cnn.AddScheduler(ss.StepLR)
	cnn.SetNEpochs(250)
	cnn.SetOpStep(100)
	cnn.TrainNN(rs_pcc=True)
	cnn.SaveParameters()
	cnn.SaveLoss()
	cnn.PlotLoss(training = True)

def Predict():
	predict = CNNPredict()
	predict.SetDevice('cuda')
	#predict.SetDevice('cpu')
	predict.SetModel(NNModel)
	predict.SetExpData('expdata.npy', mask=500, square_root=True)
	predict.SetTrainedNN("CP.pth")
	predict.SetOutputFile('output.npy')
	predict.SetLRStepSize(25)
	predict.AddLR(1e-4)
	predict.AddLR(5e-4)
	#predict.AddLR(1e-4)
	#predict.AddLR(5e-5)
	predict.SetGamma(0.9)
	predict.AddOptimiser(optim.ASGD)
	predict.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
	#predict.AddOptimiser(optim.ASGD)
	#predict.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
	predict.AddScheduler(ss.StepLR)
	predict.AddScheduler(ss.StepLR)
	#predict.AddScheduler(ss.StepLR)
	#predict.AddScheduler(ss.StepLR)
	predict.SetNEpochs(250)
	predict.SetOpStep(10)
	predict.TransferPredict()
	predict.SaveTrainLoss()
	predict.PlotLoss(training = False)

Train()
#Predict()