from cnnphase import *

cnn = CNNTrain()
cnn.SetDevice('cuda')
cnn.SetInputData('fs_amps.npy')
cnn.SetTargetData('rs_objs.npy')
cnn.SetModel(NNModel)
cnn.SetValidSize(0.1)
cnn.SplitData()
cnn.SetBatchSize(5)
cnn.LoadSplitTrain(loadtype='train')
cnn.LoadSplitTrain(loadtype='test')
#cnn.LoadWeights("CP.pth")
cnn.InitialiseWeights(nn.init.kaiming_normal_, mode='fan_in', nonlinearity='leaky_relu')
#cnn.InitialiseWeights(nn.init.xavier_normal_)
cnn.SetLRStepSize(25)
cnn.AddLR(1e-4)
cnn.AddLR(1e-5)
cnn.SetGamma(0.75)
cnn.AddOptimiser(optim.ASGD)
cnn.AddOptimiser(optim.Adam, amsgrad=True, eps=1e-8)
#cnn.AddOptimiser(optim.SGD, momentum=0.9)
#cnn.AddOptimiser(optim.RMSprop, alpha=0.99, eps=1e-08, weight_decay=0, momentum=0.9, centered=False)
cnn.AddScheduler(ss.StepLR)
cnn.AddScheduler(ss.StepLR)
cnn.SetNEpochs(600)
cnn.SetOpStep(100)
cnn.TrainNN(rs_pcc=False)
cnn.SaveParameters()
cnn.PlotLoss()